export const DIRECTIONS = [
  {
    id: 'voice',
    name: 'Голос',
    icon: '🎵',
    color: '#D4A574',
    colorLight: 'rgba(212, 165, 116, 0.15)',
    description: 'Раскрытие голоса, резонаторы, звук как терапия',
    topics: ['Раскрытие голоса', 'Резонаторы', 'Звук как терапия', 'Работа с зажимами', 'Пение и вибрации'],
  },
  {
    id: 'nutrition',
    name: 'Питание',
    icon: '🌿',
    color: '#7A9B6D',
    colorLight: 'rgba(122, 155, 109, 0.15)',
    description: 'Осознанное питание, баланс, протоколы восстановления',
    topics: ['Осознанное питание', 'Баланс', 'Протоколы восстановления', 'Детокс без крайностей', 'Пищевые привычки'],
  },
  {
    id: 'breath',
    name: 'Дыхание',
    icon: '🌬️',
    color: '#A8C5DA',
    colorLight: 'rgba(168, 197, 218, 0.15)',
    description: 'Базовые дыхательные техники, антистресс-практики',
    topics: ['Базовые дыхательные техники', 'Глубинное дыхание', 'Антистресс-практики', 'Энергетическое дыхание'],
  },
  {
    id: 'energy',
    name: 'Энергия',
    icon: '✨',
    color: '#C4B5D4',
    colorLight: 'rgba(196, 181, 212, 0.15)',
    description: 'Базовые формы цигун, потоки энергии',
    topics: ['Базовые формы цигун', 'Потоки энергии', 'Центрирование', 'Работа с внутренним ресурсом'],
  },
  {
    id: 'dance',
    name: 'Танец',
    icon: '💃',
    color: '#E8B4A0',
    colorLight: 'rgba(232, 180, 160, 0.15)',
    description: 'Свободное движение, телесное выражение',
    topics: ['Свободное движение', 'Телесное выражение', 'Пластика', 'Ритм'],
  },
  {
    id: 'water',
    name: 'Вода',
    icon: '💧',
    color: '#7EB8D0',
    colorLight: 'rgba(126, 184, 208, 0.15)',
    description: 'Практики у воды, гидротерапия, осознанное плавание',
    topics: ['Практики у воды', 'Гидротерапия', 'Осознанное плавание', 'Контакт с природой'],
  },
  {
    id: 'music',
    name: 'Музыка',
    icon: '🎶',
    color: '#C9A96E',
    colorLight: 'rgba(201, 169, 110, 0.15)',
    description: 'Музыкальная медитация, ритм и состояние',
    topics: ['Музыкальная медитация', 'Ритм и состояние', 'Влияние частот', 'Работа с восприятием'],
  },
];

export const PRACTICES = [
  {
    id: '1',
    title: 'Утреннее дыхание силы',
    direction: 'breath',
    duration: 20,
    level: 'beginner' as const,
    format: 'video' as const,
    premium: false,
    image: 'https://images.unsplash.com/photo-1758272422634-e8ed8e252a14?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGJyZWF0aGluZyUyMGV4ZXJjaXNlJTIwcGVhY2VmdWx8ZW58MXx8fHwxNzcwNTM3NDc5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Практика утреннего дыхания для энергичного начала дня. Пробуждение тела через осознанное дыхание.',
    instructorId: '2',
    fullDescription: 'Эта практика разработана для мягкого пробуждения тела и ума через серию дыхательных упражнений. Вы научитесь техникам, которые наполняют энергией, снимают утреннюю вялость и настраивают на продуктивный день. Практика включает диафрагмальное дыхание, попеременное дыхание через ноздри и энергизирующее дыхание «Капалабхати».',
    chapters: [
      { title: 'Введение и настройка', duration: 3 },
      { title: 'Диафрагмальное дыхание', duration: 5 },
      { title: 'Попеременное дыхание', duration: 5 },
      { title: 'Энергизирующее дыхание', duration: 4 },
      { title: 'Интеграция и завершение', duration: 3 },
    ],
    rating: 4.8,
    reviewCount: 124,
    completions: 1890,
  },
  {
    id: '2',
    title: 'Звуковая медитация с поющими чашами',
    direction: 'voice',
    duration: 30,
    level: 'intermediate' as const,
    format: 'audio' as const,
    premium: true,
    image: 'https://images.unsplash.com/photo-1738193179197-bac79086bdbf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaW5naW5nJTIwYm93bCUyMHNvdW5kJTIwaGVhbGluZyUyMHRoZXJhcHl8ZW58MXx8fHwxNzcwNTM3NDgwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Глубокая звуковая практика с тибетскими поющими чашами для гармонизации и расслабления.',
    instructorId: '1',
    fullDescription: 'Погрузитесь в мир звуковой терапии с тибетскими поющими чашами. Эта практика использует вибрации различных частот для глубокого расслабления, гармонизации энергетических центров и восстановления внутреннего баланса. Вы научитесь слушать обертона и чувствовать, как звук проходит через тело.',
    chapters: [
      { title: 'Подготовка к практике', duration: 4 },
      { title: 'Настройка на звук', duration: 6 },
      { title: 'Глубокая звуковая медитация', duration: 12 },
      { title: 'Работа с обертонами', duration: 5 },
      { title: 'Плавное завершение', duration: 3 },
    ],
    rating: 4.9,
    reviewCount: 89,
    completions: 1245,
  },
  {
    id: '3',
    title: 'Осознанное питание: основы',
    direction: 'nutrition',
    duration: 45,
    level: 'beginner' as const,
    format: 'video' as const,
    premium: false,
    image: 'https://images.unsplash.com/photo-1760120067369-1e5138b8d3ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwZm9vZCUyMG1pbmRmdWwlMjBlYXRpbmclMjBuYXR1cmFsfGVufDF8fHx8MTc3MDUzNzQ4MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Введение в практику осознанного питания. Научитесь слушать своё тело и выбирать подходящую пищу.',
    instructorId: '4',
    fullDescription: 'Курс «Осознанное питание» помогает выстроить здоровые отношения с едой. Вы узнаете, как распознавать истинный голод, выбирать продукты осознанно и получать удовольствие от каждого приёма пищи. Практика основана на принципах аюрведы и современной нутрициологии.',
    chapters: [
      { title: 'Что такое осознанное питание', duration: 8 },
      { title: 'Голод vs привычка', duration: 10 },
      { title: 'Принципы баланса', duration: 12 },
      { title: 'Практика осознанного приёма пищи', duration: 10 },
      { title: 'Создание плана питания', duration: 5 },
    ],
    rating: 4.7,
    reviewCount: 156,
    completions: 2310,
  },
  {
    id: '4',
    title: 'Свободный танец: пробуждение тела',
    direction: 'dance',
    duration: 40,
    level: 'beginner' as const,
    format: 'live' as const,
    premium: true,
    image: 'https://images.unsplash.com/photo-1761882667926-b4f9307f3772?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjBkYW5jZSUyMG1vdmVtZW50JTIwZnJlZWRvbXxlbnwxfHx8fDE3NzA1Mzc0ODB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Раскройте свободу движения через танец. Практика для освобождения тела от зажимов и напряжения.',
    instructorId: '3',
    fullDescription: 'Свободный танец — это практика, где нет правильных или неправильных движений. Ваше тело — инструмент выражения. Мы начнём с мягкого разогрева, перейдём к исследованию различных качеств движения и завершим танцевальной медитацией. Эта практика снимает зажимы, освобождает эмоции и возвращает радость движения.',
    chapters: [
      { title: 'Разогрев и заземление', duration: 8 },
      { title: 'Волны и потоки', duration: 10 },
      { title: 'Ритмические паттерны', duration: 10 },
      { title: 'Свободное выражение', duration: 8 },
      { title: 'Танцевальная медитация', duration: 4 },
    ],
    rating: 4.6,
    reviewCount: 72,
    completions: 890,
  },
  {
    id: '5',
    title: 'Цигун: утренний поток',
    direction: 'energy',
    duration: 25,
    level: 'intermediate' as const,
    format: 'video' as const,
    premium: true,
    image: 'https://images.unsplash.com/photo-1655970580622-4a547789c850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxxaWdvbmclMjB0YWklMjBjaGklMjBlbmVyZ3klMjBwcmFjdGljZXxlbnwxfHx8fDE3NzA1Mzc0ODF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Комплекс цигун для наполнения энергией и центрирования. Работа с потоками и внутренним ресурсом.',
    instructorId: '2',
    fullDescription: 'Утренний комплекс цигун «Поток жизни» включает 8 базовых форм для активации энергетических каналов. Практика мягко пробуждает тело, наполняет жизненной силой ци и создаёт внутреннюю устойчивость на весь день. Подходит для тех, кто уже знаком с основами цигун.',
    chapters: [
      { title: 'Стойка и центрирование', duration: 4 },
      { title: 'Разминка суставов', duration: 5 },
      { title: 'Формы цигун (1–4)', duration: 7 },
      { title: 'Формы цигун (5–8)', duration: 6 },
      { title: 'Собирание энергии', duration: 3 },
    ],
    rating: 4.9,
    reviewCount: 203,
    completions: 3120,
  },
  {
    id: '6',
    title: 'Практика у воды: осознанное плавание',
    direction: 'water',
    duration: 35,
    level: 'beginner' as const,
    format: 'outdoor' as const,
    premium: false,
    image: 'https://images.unsplash.com/photo-1760904292852-09d2cbb2e36f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvY2VhbiUyMHN3aW1taW5nJTIwcGVhY2VmdWwlMjB3YXRlciUyMG5hdHVyZXxlbnwxfHx8fDE3NzA1Mzc0ODF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Практика осознанного контакта с водой. Релаксация, восстановление и единение с природной стихией.',
    instructorId: '3',
    fullDescription: 'Вода — стихия трансформации и очищения. Эта практика учит осознанному взаимодействию с водой: от простого погружения рук до полного плавания в медитативном состоянии. Вы научитесь чувствовать воду как живую среду и использовать её целительные свойства.',
    chapters: [
      { title: 'Подготовка и настройка', duration: 5 },
      { title: 'Контакт с водой', duration: 8 },
      { title: 'Осознанное погружение', duration: 10 },
      { title: 'Медитативное плавание', duration: 8 },
      { title: 'Благодарность стихии', duration: 4 },
    ],
    rating: 4.5,
    reviewCount: 67,
    completions: 780,
  },
  {
    id: '7',
    title: 'Музыкальная медитация: частоты гармонии',
    direction: 'music',
    duration: 30,
    level: 'beginner' as const,
    format: 'audio' as const,
    premium: false,
    image: 'https://images.unsplash.com/photo-1579755219478-90d1f9971581?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNpYyUyMG1lZGl0YXRpb24lMjBwZWFjZWZ1bCUyMGluc3RydW1lbnRzfGVufDF8fHx8MTc3MDUzNzQ4M3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Медитация через музыку. Используем силу частот для глубокого расслабления и восстановления.',
    instructorId: '1',
    fullDescription: 'Музыкальная медитация с использованием целительных частот 432 Гц и 528 Гц. Вы узнаете, как разные частоты влияют на состояние тела и сознания, научитесь входить в глубокое медитативное состояние через звук и использовать музыку как инструмент ежедневного восстановления.',
    chapters: [
      { title: 'Введение в мир частот', duration: 5 },
      { title: 'Частота 432 Гц — гармония', duration: 8 },
      { title: 'Частота 528 Гц — трансформация', duration: 8 },
      { title: 'Свободное слушание', duration: 6 },
      { title: 'Интеграция', duration: 3 },
    ],
    rating: 4.7,
    reviewCount: 98,
    completions: 1560,
  },
  {
    id: '8',
    title: 'Голосовая терапия: освобождение звука',
    direction: 'voice',
    duration: 35,
    level: 'advanced' as const,
    format: 'live' as const,
    premium: true,
    image: 'https://images.unsplash.com/photo-1738193179197-bac79086bdbf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaW5naW5nJTIwYm93bCUyMHNvdW5kJTIwaGVhbGluZyUyMHRoZXJhcHl8ZW58MXx8fHwxNzcwNTM3NDgwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Продвинутая практика работы с голосом. Освобождение зажимов, раскрытие резонаторов.',
    instructorId: '1',
    fullDescription: 'Продвинутая практика для тех, кто готов к глубокой работе с голосом. Мы исследуем резонаторы тела, работаем с вибрацией и обертонами. Практика помогает освободить голос от зажимов, расширить диапазон и почувствовать терапевтическую силу собственного звука.',
    chapters: [
      { title: 'Разогрев голосового аппарата', duration: 6 },
      { title: 'Работа с резонаторами', duration: 8 },
      { title: 'Обертонное пение', duration: 10 },
      { title: 'Голосовая импровизация', duration: 7 },
      { title: 'Тишина и интеграция', duration: 4 },
    ],
    rating: 4.8,
    reviewCount: 45,
    completions: 430,
  },
  {
    id: '9',
    title: 'Антистресс-дыхание',
    direction: 'breath',
    duration: 15,
    level: 'beginner' as const,
    format: 'video' as const,
    premium: false,
    image: 'https://images.unsplash.com/photo-1643184012410-0d0c9070e575?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzZXJlbmUlMjB5b2RhJTIwbWVkaXRhdGlvbiUyMG5hdHVyZSUyMGxpZ2h0fGVufDF8fHx8MTc3MDUzNzQ3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    description: 'Быстрая практика для снятия стресса и тревожности. Техники, которые работают за 15 минут.',
    instructorId: '2',
    fullDescription: 'Экспресс-практика для моментального снятия стресса. Три мощных дыхательных техники, которые можно использовать в любой ситуации: на работе, дома или в транспорте. Вы освоите технику «4-7-8», когерентное дыхание и быстрое расслабление через выдох.',
    chapters: [
      { title: 'Оценка текущего состояния', duration: 2 },
      { title: 'Техника «4-7-8»', duration: 4 },
      { title: 'Когерентное дыхание', duration: 5 },
      { title: 'Расслабление через выдох', duration: 3 },
      { title: 'Завершение', duration: 1 },
    ],
    rating: 4.9,
    reviewCount: 312,
    completions: 5670,
  },
];

export const INSTRUCTORS = [
  {
    id: '1',
    name: 'Елена Светлова',
    specializations: ['voice', 'music'],
    bio: 'Мастер звуковой терапии с 15-летним опытом. Работала в клиниках Индии и Тибета. Преподаёт технику обертонного пения.',
    image: 'https://images.unsplash.com/photo-1765248149215-b0c913b904fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWxsbmVzcyUyMGluc3RydWN0b3IlMjBwb3J0cmFpdCUyMHdvbWFufGVufDF8fHx8MTc3MDUzNzQ4MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    practiceCount: 42,
  },
  {
    id: '2',
    name: 'Дмитрий Волков',
    specializations: ['energy', 'breath'],
    bio: 'Практик цигун и дыхательных техник. Обучался у мастеров Китая. Автор методики «Поток жизни» для городских жителей.',
    image: 'https://images.unsplash.com/photo-1758599879906-91085de59ccd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b2RhJTIwdGVhY2hlciUyMHBvcnRyYWl0JTIwbWFuJTIwY2FsbXxlbnwxfHx8fDE3NzA1Mzc0ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    practiceCount: 38,
  },
  {
    id: '3',
    name: 'Анна Березина',
    specializations: ['dance', 'water'],
    bio: 'Хореограф и практик телесной терапии. Создатель метода «Свободное тело». Сертифицированный инструктор аквайоги.',
    image: 'https://images.unsplash.com/photo-1764942687903-3a5ce0cfbebc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWxsbmVzcyUyMHJldHJlYXQlMjBuYXR1cmUlMjBzcGElMjBwZWFjZWZ1bHxlbnwxfHx8fDE3NzA1Mzc0ODN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    practiceCount: 31,
  },
  {
    id: '4',
    name: 'Марина Озерова',
    specializations: ['nutrition', 'water'],
    bio: 'Нутрициолог и специалист по осознанному питанию. Практик аюрведы. Автор программ детокса без крайностей.',
    image: 'https://images.unsplash.com/photo-1643184012410-0d0c9070e575?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzZXJlbmUlMjB5b2RhJTIwbWVkaXRhdGlvbiUyMG5hdHVyZSUyMGxpZ2h0fGVufDF8fHx8MTc3MDUzNzQ3OXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    practiceCount: 27,
  },
];

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Бесплатный',
    price: 0,
    period: '',
    features: [
      'Доступ к 5 базовым практикам',
      'Диагностика (1 раз)',
      'Колесо баланса',
      'Рекомендации направлений',
    ],
    highlighted: false,
  },
  {
    id: 'basic',
    name: 'Базовый',
    price: 990,
    period: '/мес',
    features: [
      'Все бесплатные функции',
      'Доступ к 50+ практикам',
      'Отслеживание прогресса',
      'Еженедельный план',
      '1 живая сессия в месяц',
    ],
    highlighted: false,
  },
  {
    id: 'premium',
    name: 'Премиум',
    price: 1990,
    period: '/мес',
    features: [
      'Все базовые функции',
      'Безлимитный доступ к практикам',
      'Персональные рекомендации',
      '4 живые сессии в месяц',
      'Чат с преподавателями',
      'Достижения и бейджи',
    ],
    highlighted: true,
  },
  {
    id: 'unlimited',
    name: 'Безлимит',
    price: 14990,
    period: '/год',
    features: [
      'Все премиум-функции',
      'Безлимит живых сессий',
      'Приоритетная поддержка',
      'Индивидуальный маршрут',
      'Ранний доступ к новым практикам',
      'Скидка 37%',
    ],
    highlighted: false,
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Ольга К.',
    text: 'Soul Orangerie изменила мою жизнь. Я начала с дыхательных практик после выгорания, а сейчас каждый день начинаю с цигуна и медитации.',
    direction: 'breath',
    avatar: 'О',
  },
  {
    id: '2',
    name: 'Михаил Д.',
    text: 'Колесо баланса показало мне слабые места, о которых я не задумывался. За 3 месяца работа с голосом и танцем полностью изменили мою уверенность.',
    direction: 'voice',
    avatar: 'М',
  },
  {
    id: '3',
    name: 'Алёна В.',
    text: 'Практики у воды — это невероятно. Я стала совершенно иначе чувствовать своё тело. Преподаватели здесь — настоящие мастера своего дела.',
    direction: 'water',
    avatar: 'А',
  },
];

export const DIAGNOSTIC_QUESTIONS = [
  {
    id: 1,
    question: 'Как часто вы обращаете внимание на своё дыхание в течение дня?',
    direction: 'breath',
    options: ['Никогда', 'Редко', 'Иногда', 'Часто', 'Постоянно'],
  },
  {
    id: 2,
    question: 'Как вы оцениваете свою связь с собственным голосом?',
    direction: 'voice',
    options: ['Очень слабая', 'Слабая', 'Средняя', 'Хорошая', 'Отличная'],
  },
  {
    id: 3,
    question: 'Насколько осознанно вы подходите к питанию?',
    direction: 'nutrition',
    options: ['Совсем не осознанно', 'Редко думаю об этом', 'Стараюсь', 'Осознанно', 'Полностью осознанно'],
  },
  {
    id: 4,
    question: 'Как часто вы чувствуете энергию и жизненную силу?',
    direction: 'energy',
    options: ['Почти никогда', 'Редко', 'Иногда', 'Часто', 'Постоянно'],
  },
  {
    id: 5,
    question: 'Насколько свободно вы чувствуете себя в движении?',
    direction: 'dance',
    options: ['Очень скованно', 'Скованно', 'Средне', 'Свободно', 'Полностью свободно'],
  },
  {
    id: 6,
    question: 'Как часто вы бываете у воды или работаете с водой осознанно?',
    direction: 'water',
    options: ['Никогда', 'Очень редко', 'Иногда', 'Регулярно', 'Часто'],
  },
  {
    id: 7,
    question: 'Как музыка влияет на ваше состояние?',
    direction: 'music',
    options: ['Не замечаю', 'Немного', 'Заметно', 'Сильно', 'Очень сильно'],
  },
  {
    id: 8,
    question: 'Как вы оцениваете свой уровень стресса?',
    direction: 'breath',
    options: ['Очень высокий', 'Высокий', 'Средний', 'Низкий', 'Минимальный'],
  },
  {
    id: 9,
    question: 'Как часто вы занимаетесь физическими практиками?',
    direction: 'energy',
    options: ['Никогда', 'Раз в месяц', 'Раз в неделю', '2-3 раза в неделю', 'Каждый день'],
  },
  {
    id: 10,
    question: 'Насколько вы довольны качеством своего сна?',
    direction: 'music',
    options: ['Совсем не доволен', 'Не очень', 'Средне', 'Хорошо', 'Отлично'],
  },
];

export const SCHEDULE_EVENTS = [
  {
    id: '1',
    title: 'Утренний цигун',
    instructor: 'Дмитрий Волков',
    direction: 'energy',
    date: '2026-02-09',
    time: '07:00',
    duration: 45,
    spots: 5,
    maxSpots: 20,
  },
  {
    id: '2',
    title: 'Звуковая медитация',
    instructor: 'Елена Светлова',
    direction: 'voice',
    date: '2026-02-09',
    time: '10:00',
    duration: 60,
    spots: 8,
    maxSpots: 15,
  },
  {
    id: '3',
    title: 'Свободный танец',
    instructor: 'Анна Березина',
    direction: 'dance',
    date: '2026-02-10',
    time: '18:00',
    duration: 50,
    spots: 12,
    maxSpots: 25,
  },
  {
    id: '4',
    title: 'Дыхательная практика',
    instructor: 'Дмитрий Волков',
    direction: 'breath',
    date: '2026-02-10',
    time: '08:00',
    duration: 30,
    spots: 3,
    maxSpots: 20,
  },
  {
    id: '5',
    title: 'Осознанное питание: мастер-класс',
    instructor: 'Марина Озерова',
    direction: 'nutrition',
    date: '2026-02-11',
    time: '12:00',
    duration: 90,
    spots: 10,
    maxSpots: 30,
  },
  {
    id: '6',
    title: 'Музыка частот',
    instructor: 'Елена Светлова',
    direction: 'music',
    date: '2026-02-12',
    time: '19:00',
    duration: 40,
    spots: 6,
    maxSpots: 15,
  },
  {
    id: '7',
    title: 'Практика у воды',
    instructor: 'Анна Березина',
    direction: 'water',
    date: '2026-02-13',
    time: '09:00',
    duration: 60,
    spots: 15,
    maxSpots: 20,
  },
];

export const LEVEL_LABELS: Record<string, string> = {
  beginner: 'Начинающий',
  intermediate: 'Средний',
  advanced: 'Продвинутый',
};

export const FORMAT_LABELS: Record<string, string> = {
  video: 'Видео',
  audio: 'Аудио',
  live: 'Живая сессия',
  outdoor: 'На природе',
};

export const ADMIN_USERS = [
  { id: '1', name: 'Алина Морозова', email: 'alina@mail.ru', role: 'student' as const, plan: 'premium', joinDate: '2025-09-15', lastActive: '2026-02-08', practicesDone: 47 },
  { id: '2', name: 'Иван Петров', email: 'ivan.p@gmail.com', role: 'student' as const, plan: 'basic', joinDate: '2025-11-03', lastActive: '2026-02-07', practicesDone: 22 },
  { id: '3', name: 'Мария Сидорова', email: 'maria.s@yandex.ru', role: 'student' as const, plan: 'free', joinDate: '2026-01-20', lastActive: '2026-02-06', practicesDone: 5 },
  { id: '4', name: 'Елена Светлова', email: 'elena.s@soulorangerie.com', role: 'instructor' as const, plan: 'unlimited', joinDate: '2025-06-01', lastActive: '2026-02-08', practicesDone: 0 },
  { id: '5', name: 'Дмитрий Волков', email: 'dmitry.v@soulorangerie.com', role: 'instructor' as const, plan: 'unlimited', joinDate: '2025-06-01', lastActive: '2026-02-08', practicesDone: 0 },
  { id: '6', name: 'Ольга Кузнецова', email: 'olga.k@mail.ru', role: 'student' as const, plan: 'unlimited', joinDate: '2025-08-10', lastActive: '2026-02-08', practicesDone: 89 },
  { id: '7', name: 'Сергей Николаев', email: 'sergey.n@gmail.com', role: 'student' as const, plan: 'premium', joinDate: '2025-10-22', lastActive: '2026-02-05', practicesDone: 34 },
  { id: '8', name: 'Анна Березина', email: 'anna.b@soulorangerie.com', role: 'instructor' as const, plan: 'unlimited', joinDate: '2025-06-01', lastActive: '2026-02-08', practicesDone: 0 },
  { id: '9', name: 'Татьяна Лебедева', email: 'tatyana.l@yandex.ru', role: 'student' as const, plan: 'basic', joinDate: '2025-12-15', lastActive: '2026-02-04', practicesDone: 14 },
  { id: '10', name: 'Марина Озерова', email: 'marina.o@soulorangerie.com', role: 'instructor' as const, plan: 'unlimited', joinDate: '2025-06-01', lastActive: '2026-02-08', practicesDone: 0 },
];

export const ADMIN_STATS = {
  totalUsers: 1247,
  activeSubscriptions: 892,
  monthlyRevenue: 1_340_000,
  totalPractices: 156,
  liveSessionsThisMonth: 28,
  avgRating: 4.7,
  newUsersThisWeek: 43,
  retentionRate: 78,
};

export const ADMIN_REVENUE_CHART = [
  { month: 'Авг', revenue: 820000, users: 340 },
  { month: 'Сен', revenue: 950000, users: 520 },
  { month: 'Окт', revenue: 1050000, users: 680 },
  { month: 'Ноя', revenue: 1180000, users: 830 },
  { month: 'Дек', revenue: 1250000, users: 990 },
  { month: 'Янв', revenue: 1300000, users: 1120 },
  { month: 'Фев', revenue: 1340000, users: 1247 },
];

export const INSTRUCTOR_FEEDBACK = [
  { id: '1', studentName: 'Ольга К.', practiceTitle: 'Звуковая медитация', rating: 5, text: 'Потрясающая практика! Чувствую глубокое расслабление после каждого сеанса.', date: '2026-02-07' },
  { id: '2', studentName: 'Михаил Д.', practiceTitle: 'Голосовая терапия', rating: 4, text: 'Очень интересный подход. Хотелось бы больше упражнений на резонаторы.', date: '2026-02-06' },
  { id: '3', studentName: 'Алина М.', practiceTitle: 'Музыкальная медитация', rating: 5, text: 'Частоты 528 Гц действительно работают. Засыпаю моментально!', date: '2026-02-05' },
  { id: '4', studentName: 'Сергей Н.', practiceTitle: 'Звуковая медитация', rating: 5, text: 'Лучшая практика на платформе. Елена — удивительный преподаватель.', date: '2026-02-04' },
];